spring.application.name=desafio-dio-spring

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:h2:file:./data/cnpjdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cache
spring.cache.type=simple
spring.cache.cache-names=cnpjCache

# Logging
logging.level.com.cnpjfinder=DEBUG
logging.level.org.springframework.web=INFO